### ISSUE TITLE
Update group based on item changes

### ISSUE THREAD

**Issue by rk-nova** [tetele/hvac_group#67]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/tetele/hvac_group/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It would be great to have the goups update when the items change.  This would make the consistant with other groups in HA, and 
make things like having multiple groups work.  For example, I want to have a single group for each floor, and then a master group for all heaters.  But right now, these would never stay in sync.

![Recording 2024-02-09 120443](https://github.com/tetele/hvac_group/assets/9308808/314135a3-9be2-4012-bf5a-9fafbe3a0663)

### Describe the solution you'd like

My primary ask here is for the target temperatures to sync in both directions.  When one or more items change, the value reported on the group should show the average (and not update the values of any other items).  And when the value on the group is changed, it shoud update all items in the group.

It would also be good for the mode to reflect those of the group items, but that's less important that the target temperatures.

### Describe alternatives you've considered

The only alternitive is to not include thermostats in multiple groups and to only interact though the group.  But that requires changes to more automations, and does not allow for as fine grained of control when multiple thermostats of the same type are in a group.

### Additional context

None

**Comment by MakaanPL** [comment]
I have two TRV in the same room. While the automation of the boiler uses each of these individually, I just used your helper to change target temperature on both at the same time (manual + schedule). However, it seems like there's only one-way sync of temperature (group->members). Turning on/off doesn't work at all, but my TRVs use hvac_action.

 Ideally, any change of temp/mode, especially via manual knob on one TRV, should propagate to other members. But I understand some people would prefer the average.

@tetele could you please update the readme to inform clearly what it does and what it doesn't? Also I'd like to know more about the hvac_action, how exactly does it follow the state of members, and what is the logic of it? Or does it have its own hvac_action based purely on temperature difference between sensor and setting?

**Comment by tetele** [comment]
> could you please update the readme to inform clearly what it does and what it doesn't?

Sure.

> Or does it have its own hvac_action based purely on temperature difference between sensor and setting?

Yes

**Comment by dt2086** [comment]
Hey there - this is kinda annoying so I wrote a quick Blueprint that allows you to monitor 2 radiators and update a group accordingly... it's a little quick and dirty, as I only have groups of 2 in my house, but it could probably be modified to extend the HVAC group functionality for those that need it.


```
blueprint:
  name: HVAC Group Sync
  description: Passes a temperature value to a number on change.
  domain: automation
  author: Dan T.
  input:
    target_group_entity:
      name: Group
      selector:
        entity:
          filter:
            domain: climate
    watch_rad_01_entity:
      name: Rad01
      selector:
          entity:
            filter:
              domain: climate
    watch_rad_02_entity:
      name: Rad02
      selector:
          entity:
            filter:
              domain: climate

mode: restart
max_exceeded: silent

triggers:
  - entity_id: !input watch_rad_01_entity
    attribute: temperature
    trigger: state
    alias: "The radiator is set to a new target temerature"
    id: RadTrig1

  - entity_id: !input watch_rad_02_entity
    attribute: temperature
    trigger: state
    alias: "The radiator is set to a new target temerature"
    id: RadTrig2

variables:
  rad_entity_01: !input watch_rad_01_entity
  rad_entity_02: !input watch_rad_02_entity
  group_entity: !input target_group_entity

actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - RadTrig1
        sequence:
          - metadata: {}
            data:
              temperature: >
                {{ state_attr( rad_entity_01, 'temperature') }}
            target:
              entity_id: !input target_group_entity
            action: climate.set_temperature
      - conditions:
          - condition: trigger
            id:
              - RadTrig2
        sequence:
          - metadata: {}
            data:
              temperature: >
                {{ state_attr( rad_entity_02, 'temperature') }}
            target:
              entity_id: !input target_group_entity
            action: climate.set_temperature
```
